# Generated by Django 4.1.1 on 2023-04-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmania_website', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
