# Generated by Django 4.1.1 on 2023-04-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmania_website', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
    ]
