# Generated by Django 4.1.1 on 2023-05-04 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodmania_website', '0005_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Pending', 'Pending')], default='Pending', max_length=10, null=True)),
                ('provider_order_id', models.CharField(max_length=40)),
                ('payment_id', models.CharField(max_length=40)),
                ('signature_id', models.CharField(max_length=150)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='foodmania_website.order'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mypayments', to=settings.AUTH_USER_MODEL),
        ),
    ]
