# Generated by Django 4.1.1 on 2023-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmania_website', '0006_orderpayment_alter_order_total_amount_delete_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Deleted', 'Deleted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
