"""
Django's settings for rms project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = 'user.User'

LOGIN_REDIRECT_URL = reverse_lazy('foodmania_website:website')

LOGIN_URL = reverse_lazy('user:login')

LOGOUT_REDIRECT_URL = reverse_lazy('user:login')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^%*p2+*+-=pz&sx*n@%%69illk5+v*$m)x0s7owrtq9=k(_yjj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# CSRF_TRUSTED_ORIGINS = ['https://0ce4-2405-204-8386-9f68-596d-4395-a910-7cae.ngrok-free.app']

CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'django_filters',
    'foodmania',
    'user',
    'foodmania_website',
    'import_export',
    'widget_tweaks',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'rms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'my_tags': 'rms.template_tags.custom_template',
            },
        },
    },
]

WSGI_APPLICATION = 'rms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
]

JAZZMIN_SETTINGS = {
    "site_title": "FOODMANIA",
    "site_logo": "images/foodmania_icon.jpeg",
    "welcome_sign": "WELCOME TO FOODMANIA",
    "copyright": "Foodmania",
    "search_model": ["user.User", "foodmania_website.Order", "foodmania.Food"],
    "topmenu_links": [
        {"model": "user.User"},
        {"model": "foodmania_website.Order"}
    ],
    "usermenu_links": [
        {
            "name": "My admin site",
            "url": "foodmania_website:dashboard",
            "icon": "fas fa-globe"
        },
        {
            "name": "My website",
            "url": "foodmania_website:website",
            "icon": "fas fa-globe"
        },
        {
            "name": "Support",
            "url": "https://github.com/PakshalTrootech",
            "icon": "fas fa-comments",
            "new_window": True
        }
    ],
    "icons": {
        "account.EmailAddress": "fas fa-at",
        "foodmania.Category": "fas fa-clipboard-list",
        "foodmania.Food": "fas fa-utensils",
        "foodmania_website.CartItem": "fas fa-luggage-cart",
        "foodmania_website.Cart": "fas fa-shopping-cart",
        "foodmania_website.OrderPayment": "fas fa-file-invoice",
        "foodmania_website.Order": "fas fa-book",
        "sites.Site": "fas fa-globe",
        "socialaccount.SocialAccount": "fas fa-user-circle",
        "socialaccount.SocialToken": "fas fa-key",
        "socialaccount.SocialApp": "fab fa-adn",
        "user.UserAddress": "fas fa-address-book",
        "user.User": "fas fa-users"
    },
    "show_ui_builder": True
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pakshal.shah@trootech.com'
EMAIL_HOST_PASSWORD = 'oCBs#@123'
EMAIL_FILE_PATH = BASE_DIR / 'emails'

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
MEDIA_URL = "/media/"

RAZORPAY_KEY_ID = 'rzp_test_3LLVGVG9cmu4iZ'
RAZORPAY_KEY_SECRET = 'YiUJqqhL0vehUSrTCXNbVSLy'

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

SITE_ID = 2
SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
