# Generated by Django 4.1.1 on 2023-04-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmania', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-id']},
        ),
    ]
