# Generated by Django 4.1.1 on 2023-04-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmania', '0003_alter_category_options_alter_food_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
    ]
