# Generated by Django 4.1.1 on 2023-04-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmania', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
